### ISSUE TITLE
TV shows not downloading in latest plex_debrid version

### ISSUE THREAD

**Issue by ppogorze** [itsToggle/plex_debrid#145]
Fresh config, commit [da92814](https://github.com/itsToggle/plex_debrid/commit/da928141bcab16ff753ada8827e0463cd6f581f5)

Everything works except tv shows (Plex library id is ok). Log below:
`[2022-09-23 19:41:53.921223] took 0.0s
Exception in thread Thread-37:
Traceback (most recent call last):
  File "/Users/pp/.pyenv/versions/3.8.13/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/pp/.pyenv/versions/3.8.13/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "plex_rd.py", line 3094, in download
    result[index] = cls.download(library=library,parentReleases=parentReleases)
  File "plex_rd.py", line 546, in download
    while len(self.Releases) == 0 and i <= retries:
UnboundLocalError: local variable 'i' referenced before assignment
[2022-09-23 19:41:53.942116] took 0.0s
`

**Comment by nammminn2** [comment]
yeah i got the same error as well https://share.cleanshot.com/UbLvxX

**Comment by itsToggle** [comment]
Hey sorry you guys.. I've updated the script and it should now run again.
