### ISSUE TITLE
Editing show menu on startup setting crashes the script

### ISSUE THREAD

**Issue by RomEz10** [itsToggle/plex_debrid#16]
Hello.
I was attempting to edit the setting not to show menu on startup (inputs are 2411 the last '1' causes the crash) but when you attempt to edit it the script crashes with this traceback:

Traceback (most recent call last):
  File "/home/rom/plex_rd.py", line 2304, in <module>
    ui.run()
  File "/home/rom/plex_rd.py", line 2272, in run
    ui.options()
  File "/home/rom/plex_rd.py", line 2221, in options
    option.input()
  File "/home/rom/plex_rd.py", line 1750, in input
    func()
  File "/home/rom/plex_rd.py", line 2200, in settings
    setting.input()
  File "/home/rom/plex_rd.py", line 1787, in input
    clipboard.copy(getattr(self.cls,self.key))
  File "/home/rom/.local/lib/python3.10/site-packages/pyperclip/__init__.py", line 659, in lazy_load_stub_copy
    return copy(text)
  File "/home/rom/.local/lib/python3.10/site-packages/pyperclip/__init__.py", line 336, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error 

OS is arch-linux but the same error also happens on freebsd

Would be happy to give more info if required.

**Comment by itsToggle** [comment]
Thanks for reporting this. Pyperclip ist used to copy the current setting value into the cipboard, as a way to make editing a setting easier. 
I will probably remove pyperclip from the imported modules, since the benefit is minimal and OS compatability is apperently too limited. 
I have already done so in the 'android' branch (https://github.com/itsToggle/plex_debrid/tree/android), since android doesnt support pyperclip either. 
Until I decide what to do you can use that version :)

**Comment by RomEz10** [comment]
Ok thanks man.

**Comment by itsToggle** [comment]
Alright, Ive decided to remove it from the main branch aswell. The benefit is not worth the limited compatability.
