### ISSUE TITLE
Crashing after running for a while, macOS Monterey

### ISSUE THREAD

**Issue by magnu5** [itsToggle/plex_debrid#26]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "plex_rd.py", line 1712, in run
    element.download(library=library)
  File "plex_rd.py", line 328, in download
    self.Seasons = self.uncollected(library)
  File "plex_rd.py", line 303, in uncollected
    Seasons.remove(season)
ValueError: list.remove(x): x not in list
^CTraceback (most recent call last):
  File "plex_rd.py", line 2347, in <module>
    ui.run()
  File "plex_rd.py", line 2315, in run
    ui.options()
  File "plex_rd.py", line 2248, in options
    option.input()
  File "plex_rd.py", line 1774, in input
    func()
  File "plex_rd.py", line 1751, in run
    text = input("")

**Comment by itsToggle** [comment]
Should be fixed in the latest version, I hope. I'll leave the issue open for now, please report if it happens again :)

**Comment by itsToggle** [comment]
That looks like a jackett misconfiguration. Have you entered a jackett base url? It should be this one, If you have default Jackett settings: http://127.0.0.1:9117
