### ISSUE TITLE
Plex Debrid Script Error

### ISSUE THREAD

**Issue by inputuserhere** [itsToggle/plex_debrid#262]
I'm running it as sudo. After I add in my server URL the second time, this error comes up.

Traceback (most recent call last):
  File "/home/plex/plex_debrid-main/main.py", line 19, in <module>
    ui.run(config_dir)
  File "/home/plex/plex_debrid-main/ui/__init__.py", line 309, in run
    if setup():
  File "/home/plex/plex_debrid-main/ui/__init__.py", line 236, in setup
    setting.setup()
  File "/home/plex/plex_debrid-main/settings/__init__.py", line 235, in setup
    service.setup(service, new=True)
  File "/home/plex/plex_debrid-main/content/services/plex.py", line 365, in setup
    for index,section in enumerate(response.MediaContainer.Directory):
AttributeError: 'NoneType' object has no attribute 'MediaContainer'

Trying to run main.py again results in:

Traceback (most recent call last):
  File "/home/plex/plex_debrid-main/main.py", line 1, in <module>
    import ui
  File "/home/plex/plex_debrid-main/ui/__init__.py", line 1, in <module>
    from base import *
  File "/home/plex/plex_debrid-main/base/__init__.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by itsToggle** [comment]
You seem to be missing the "requests" python module. Did you install the modules from the requirements.txt file? (First step)

**Comment by inputuserhere** [comment]
Yes.

**Comment by itsToggle** [comment]
make sure you install the modules for the python version you are running the script with. If you've got an older python version (2.X), make sure your pip install command installs the modules for python 3.X - the command for this might be "pip3" rather than "pip", but this totally depends on your setup.

**Comment by itsToggle** [comment]
make sure the python version you are running the script with is the same version you've installed the modules for.
There is no other reason why the module would be missing otherwise.

**Comment by inputuserhere** [comment]
Sure, I'll try Discord, because even the Docker image gives me the same error. Shouldn't that have already gotten/have the requirements?
