### ISSUE TITLE
lumped bug reports from discord for internal use

### ISSUE THREAD

**Issue by itsToggle** [itsToggle/plex_debrid#323]
```[16/01/23 04:04:31] retrying download in 30min for item: top.gear.S01E10. - version/s [shows 1080p],[shows 2160p] - attempt 1/50
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home8/maxexcloo/.apps/plex_debrid/ui/__init__.py", line 377, in threaded
    element.download(library=library)
  File "/home8/maxexcloo/.apps/plex_debrid/content/classes.py", line 886, in download
    if result[0]:
TypeError: 'NoneType' object is not subscriptable
```

```[16/01/23 04:03:08] checking cache status for scraped releases on: [Real Debrid] ... [16/01/23 04:03:08] scraping sources for query "top.gear.S07E01." ... [16/01/23 04:03:08] [jackett] error: jackett couldnt be reached. Make sure your jackett base url is correctly formatted (default: http://localhost:9117).
Exception in thread Thread-385:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home8/maxexcloo/.apps/plex_debrid/content/classes.py", line 1052, in download
    result[index] = cls.download(library=library, parentReleases=parentReleases)
  File "/home8/maxexcloo/.apps/plex_debrid/content/classes.py", line 948, in download
    downloaded, retry = episode.download(library=library, parentReleases=self.Releases)
  File "/home8/maxexcloo/.apps/plex_debrid/content/classes.py", line 966, in download
    self.Releases = scraper.scrape(self.query(title), self.deviation())
  File "/home8/maxexcloo/.apps/plex_debrid/scraper/__init__.py", line 21, in scrape
    t.start()
  File "/usr/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by maxexcloo** [comment]
I can note that these issues only come up when using Jackett - in particular with FlareSolverr.
