### ISSUE TITLE
Random error during Tv Show Download..

### ISSUE THREAD

**Issue by dreulavelle** [itsToggle/plex_debrid#348]
...
[20/01/23 08:06:05] [realdebrid] error (missing torrent hash): ignoring release 'Vikings.S01E07.HDTV.x264-2HD'
[20/01/23 08:06:05] [realdebrid] error (missing torrent hash): ignoring release 'Vikings.S01E08.HDTV.x264-2HD'
[20/01/23 08:06:05] [realdebrid] error (missing torrent hash): ignoring release 'Vikings.S01E09.HDTV.x264-2HD'
[20/01/23 08:06:13] checking cache status for scraped releases on: [Real Debrid] ... done
[20/01/23 08:06:14] sorting releases for version [Default Scraping Rules] ... done - found 0 releases

```python
Exception in thread Thread-1 (threaded):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/ui/__init__.py", line 395, in threaded
    element.download(library=library)
  File "/content/classes.py", line 878, in download
    debrid_downloaded, retry = self.debrid_download()
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/content/classes.py", line 1070, in debrid_download
    releases.sort(self.Releases, self.version)
  File "/releases/__init__.py", line 1247, in __new__
    rule = subrule(rule[0], rule[1], rule[2], rule[3])
                                              ~~~~^^^
IndexError: list index out of range
```

It's frozen here.

**Comment by dreulavelle** [comment]
[20/01/23 08:44:11] [realdebrid] error (missing torrent hash): ignoring release 'Vikings.S01E05.HDTV.x264-2HD'
[20/01/23 08:44:11] [realdebrid] error (missing torrent hash): ignoring release 'Vikings.S01E06.HDTV.x264-2HD'
[20/01/23 08:44:11] [realdebrid] error (missing torrent hash): ignoring release 'Vikings.S01E07.HDTV.x264-2HD'
[20/01/23 08:44:11] [realdebrid] error (missing torrent hash): ignoring release 'Vikings.S01E08.HDTV.x264-2HD'
[20/01/23 08:44:11] [realdebrid] error (missing torrent hash): ignoring release 'Vikings.S01E09.HDTV.x264-2HD'
```python
Traceback (most recent call last):
  File "//./main.py", line 21, in <module>
    ui.run(config_dir, service_mode)
  File "/ui/__init__.py", line 343, in run
    options()
  File "/ui/__init__.py", line 237, in options
    options()
  File "/ui/__init__.py", line 237, in options
    options()
  File "/ui/__init__.py", line 237, in options
    options()
  [Previous line repeated 1 more time]
  File "/ui/__init__.py", line 236, in options
    option_.input()
  File "/ui/__init__.py", line 22, in input
    func()
  File "/ui/__init__.py", line 111, in scrape
    releases.sort(scraped_releases, obj.version)
  File "/releases/__init__.py", line 1247, in __new__
    rule = subrule(rule[0], rule[1], rule[2], rule[3])
                                              ~~~~^^^
IndexError: list index out of range
```
Tried doing a manual scrape using a TV Profile ruleset.

**Comment by itsToggle** [comment]
Did you edit the rules in the settings.json file? Don't do that.
