### ISSUE TITLE
Regex Core Error

### ISSUE THREAD

**Issue by godver3** [itsToggle/plex_debrid#515]
![7B82F177-BAEE-4698-9866-5907E49EB116](https://github.com/itsToggle/plex_debrid/assets/33110414/d18109c5-6a82-45eb-9f49-b1e00d77252f)

Getting this on 2.94.

**Comment by Tragidy** [comment]
I also am getting this issue on this version.

**Comment by KingPin** [comment]
according to people on discord they are getting this for a movie called **+1** and when checking my log I had it crash on same movie. 

```
plex-debrid  | [07/08/23 18:33:14] scraping sources [orionoid,torrentio] for query "+1.2013" ... done - found 10 releases
plex-debrid  | [07/08/23 18:33:15] scraping sources [orionoid,torrentio] for IMDB ID "tt2395385" ... done - found 10 releases
plex-debrid  | [07/08/23 18:33:16] checking cache status for scraped releases on: [Real Debrid] ... done
plex-debrid  | [07/08/23 18:33:17] sorting releases for version [1080p SDR] ... done - found 16 releases
plex-debrid  | Exception in thread Thread-1 (threaded):
plex-debrid  | Traceback (most recent call last):
plex-debrid  |   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
plex-debrid  |     self.run()
plex-debrid  |   File "/usr/lib/python3.11/threading.py", line 975, in run
plex-debrid  |     self._target(*self._args, **self._kwargs)
plex-debrid  |   File "/plex_debrid/ui/__init__.py", line 497, in threaded
plex-debrid  |     element.download(library=library)
plex-debrid  |   File "/plex_debrid/content/classes.py", line 1149, in download
plex-debrid  |     debrid_downloaded, retry = self.debrid_download(force=False)
plex-debrid  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
plex-debrid  |   File "/plex_debrid/content/classes.py", line 1446, in debrid_download
plex-debrid  |     if debrid.download(self, stream=True,force=force):
plex-debrid  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
plex-debrid  |   File "/plex_debrid/debrid/__init__.py", line 24, in download
plex-debrid  |     if service.download(element, stream=stream, query=query, force=force):
plex-debrid  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
plex-debrid  |   File "/plex_debrid/debrid/services/realdebrid.py", line 131, in download
plex-debrid  |     if regex.match(query, release.title,regex.I) or force:
plex-debrid  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
plex-debrid  |   File "/usr/lib/python3.11/site-packages/regex/regex.py", line 253, in match
plex-debrid  |     pat = _compile(pattern, flags, ignore_unused, kwargs, True)
plex-debrid  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
plex-debrid  |   File "/usr/lib/python3.11/site-packages/regex/regex.py", line 546, in _compile
plex-debrid  |     raise error(caught_exception.msg, caught_exception.pattern,
plex-debrid  | regex._regex_core.error: nothing to repeat at position 15
```

so most likely its an escaping issue, we need to figure out a regex for it.

**Comment by itsToggle** [comment]
Thanks for reporting and testing this. It seems we need to escape the special characters in the media titles correctly. This is already done somewhere, but apparently there are ways for titles to circumvent the escaping. I'll check that out.

**Comment by itsToggle** [comment]
Thanks for reporting and testing this. It seems we need to escape the special characters in the media titles correctly. This is already done somewhere, but apparently there are ways for titles to circumvent the escaping. I'll check that out.

**Comment by thierrybla** [comment]
I am also running into this issue, is there any fix yet?
