### ISSUE TITLE
Scraping Doesn't Work with Overseerr Sync and Prowlarr

### ISSUE THREAD

**Issue by HashaRock** [itsToggle/plex_debrid#56]
Hello again! I decided to take my day out and get plex_debrid working on my Mac. However, after setting up everything I wanted, every type of scraping fails. It simply gives these errors before anything takes place. I've tried my best to figure out what's wrong but I have no clue at the moment.

2022-08-03 15:56:21.960399] scraping sources for query "pirates.of.the.caribbean.dead.men.tell.no.tales.2017" ... Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "plex_rd.py", line 2516, in scrape
    result[index] = cls(query)
  File "plex_rd.py", line 2458, in __new__
    response = scraper.prowlarr.session.get(url,headers=headers)
  File "/Users/hassaanali/Library/Python/3.8/lib/python/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/Users/hassaanali/Library/Python/3.8/lib/python/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/Users/hassaanali/Library/Python/3.8/lib/python/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/Users/hassaanali/Library/Python/3.8/lib/python/site-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/Users/hassaanali/Library/Python/3.8/lib/python/site-packages/requests/models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/api/v1/search?query=pirates.of.the.caribbean.dead.men.tell.no.tales.2017&type=search&limit=1000&offset=0': No scheme supplied. Perhaps you meant http:///api/v1/search?query=pirates.of.the.caribbean.dead.men.tell.no.tales.2017&type=search&limit=1000&offset=0?
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "plex_rd.py", line 2545, in run
    element.download(library=library)
  File "plex_rd.py", line 343, in download
    self.Releases += scraper(self.query())
  File "plex_rd.py", line 2240, in __new__
    scraped_releases += result
TypeError: 'NoneType' object is not iterable

**Comment by itsToggle** [comment]
Hey, that's an odd error. It looks like the prowlarr base url is missing, judging by the "requests.exceptions.MissingSchema: Invalid URL" line.
Try setting the base url again by going to "/Settings/Scraper/Sources/Prowlarr/Prowlarr base url".

**Comment by itsToggle** [comment]
Try entering the default url: http://127.0.0.1:9696

**Comment by HashaRock** [comment]
Wow I'm really dumb. I entered away the API Key for Prowlarr without putting in the address for the base url.

Thanks so much for that easy fix, I really had a brain fart there.

**Comment by HashaRock** [comment]
Also, don't want to open another issue but: was there any information on how plex_debrid keeps your cached torrents saved without removing it?

I remember reading it but I can't find it in the readme.md.

**Comment by itsToggle** [comment]
Easy fix :D

I'm not quite sure what you are referring to - what do you mean by keeping cached torrents saved?

If you are referring to realdebrids automatic removal of unrestricted links after 7 days: both my rclone fork and the official realdebrid WebDAV check the restricted links from finished torrents (which are not automatically removed) against the users list of unrestricted links. If a torrent is no longer unrestricted, its links are simply unrestricted again :)

**Comment by HashaRock** [comment]
Yes that exactly. usually RD takes the download out after a bit but that is great to hear!
