### ISSUE TITLE
[plex error]: could not reach plex" after te last update of Plex Debrid and Plex

### ISSUE THREAD

**Issue by arjanterheegde** [itsToggle/plex_debrid#573]
Anyone else getting the error "[plex error]: could not reach plex" after te last update of Plex Debrid?
I've updated plex debrid and Plex with the latests version and i'm getting this error... Already tried another token but still no luck.. I can react http://localhost:32400/ without any problem. Does anyone know what to do? 🙂

With debugging on Plex Debrid stops after this error:

`Exception in thread Thread-1 (threaded):
Traceback (most recent call last):
  File "/scraper/__init__.py", line 26, in scrape
    t.start()
  File "/usr/local/lib/python3.12/threading.py", line 971, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "/ui/__init__.py", line 426, in threaded
    element.download(library=library)
  File "/content/classes.py", line 1201, in download
    self.Releases += scraper.scrape(self.query(title).replace(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scraper/__init__.py", line 30, in scrape
    t.start()
  File "/usr/local/lib/python3.12/threading.py", line 971, in start
    _start_new_thread(self._bootstrap, ())`

**Comment by Jauntiness** [comment]
Same here, thanks for reporting...

**Comment by arjanterheegde** [comment]
Anyone?

**Comment by anagoor** [comment]
The problem comes from the TTY when is not present, plex debrid gives that error

What works:
docker run -v /volume1/docker/plexdebrid/config:/config --net host -ti itstoggle/plex_debrid
What does NOT work:
docker run -v /volume1/docker/plexdebrid/config:/config --net host itstoggle/plex_debrid

The problem is the second case happens when launching via docker-compose and hence the issue...

**Comment by phromaj** [comment]
I tried to launch the service in Docker Swarm (which should also apply to Docker Compose) with the following configuration, but it did not work:

```yaml
plex_debrid:
    image: itstoggle/plex_debrid
    volumes:
      - /home/XXXX/.config/appdata/plex_debrid:/config
    tty: true
    stdin_open: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
```

However, the command you provided does work. I hope the bug will be fixed soon. Thank you for your help.
